
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # The current release should be executable on PHP 7.1 and up.
  - 7.1

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-source --dev

#before_script:
#    - php ./resources/build/travis-ci.php   leave here temporarily, try to get do it without this from tavis gui

script:
    - phpunit --configuration resources/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - ./vendor/bin/test-reporter